### ISSUE TITLE
okky에서 보고 의견 남겨요.

### ISSUE THREAD

**Issue by albothyl** [BeomjunLee/ticketingServiceApi#3]
okky에서 보고 왔습니다.
10분 정도 살펴보고 의견 남겨요.

요약
- 누구나 이해하기 쉽고, 접근하기 쉽고, 수정하기 쉽고, 확장성 높은 코드를 만들려면 어떻게 해야 하는지에 대한 고민이 중요해요. 그러기 위한 가장 기본은 도메인이 무엇인가? 에 대한 이해가 기본이 되고, 도메인별로 패키지가 구성되고, 패키지에 어울리는 클래스 및 메소드 이름이 나와야 돼요. 이것에 대한 보장으로 유닛 및 기능 테스트는 필수로 존재해야 하구요.

1. 중복 코드 제거
2. 불필요한 주석 제거
3. 엔티티 변경 일자 추가
4. 도메인이 무엇이고, 어떻게 표현해야 할 지에 대한 고민 (패키지를 기능별이 아닌 도메인별로 변경해 보면 좋을것)
5. unit 테스트 없음
6. functional 테스트 없음
7. 존재하는 테스트는 대부분 자동화 되지 않고, 눈으로 확인 하기 위한 목적이 큼.
8. 불필요한 @Query 사용
9. @Data 는 어쩔수 없는 경우가 아니라면 지양할 것.
10. queryDsl에 대한 클래스 네이밍 규칙 찾아볼 것.
11. 테스트 용도와 실제 서비스 용도의 기능을 구분할 것.
12. 프로파일 적용 (local, develop, production)
13. 클래스에 Severice나 Manager 등의 이름을 지양 할 것. (너무 추상적이므로 하나의 클래스가 너무 커지므로 테스트나 레거시 코드가 되었을때 수정하기 힘듬)
14. @Transactional 에 대한 동작이 어떻게 되는지 공부할 것. (테스트에서 불필요하게 사용되는것, readOlny가 동작 하는지 확인)
15. 객체지향 5원칙을 공부하고 적용하려고 노력할 것.

**Comment by BeomjunLee** [comment]
정말 감사합니다!! 제가 늦게 확인해서 피드백 주신 부분 토대로 살펴보고 있습니다!!
혹시 괜찮으시다면 몇가지 부분에 대해 여쭤봐도 될까요??

**Comment by albothyl** [comment]
넵.
 
-----Original Message-----

**Comment by BeomjunLee** [comment]
누구나 이해하기 쉽고, 접근하기 쉽고, 수정하기 쉽고, 확장성 높은 코드를 만들려면 어떻게 해야 하는지에 대한 고민과 도메인에 대한 이해가 중요하다는 부분에 대한 말씀이 많이 와 닿았습니다.

피드백 해주신 부분을 토대로 불필요한 주석 제거와 도메인 위주로 패키지를 수정하고 엔티티의 변경일자 추가와 프로파일을 적용해보았습니다.
현재는 Mockito 를 이용한 단위 테스트를 짜보고 있습니다...! 지식이 좀 더 늘은 것 같아서 행복합니다!
제가 궁금한 몇가지 질문 하겠습니다 (번호는 조언해주신 부분에 대한 번호입니다)


**[5, 6]**  혹시 기능 테스트는 단위 테스트 보다 더 작은 단위의 기능들의 테스트들을 말씀하시는건지 궁금합니다. 
그리고 언제는 통합, 언제는 단위, 아니면 둘다 혼합해서 사용한다던지 어느 때에 어떤 테스트 방법을 사용하는게 좋은지 잘 감이 안잡힙니다..! 
예전부터 이 부분이 궁금했었는데 구글링에는 명백하게 나오지 않더라구요..

**[8]** @Query 로 네이티브 쿼리랑 Querydsl 을 둘다 적용해보려고 사용했었었습니다! 
Querydsl 이 @Query 랑 다르게 자바 코드로 작성되기 때문에 컴파일시 오류를 잡아줘서 매우 장점인 부분이 있는데 혹시 이 부분 때문에 말씀하신건지 궁금합니다!

**[9]** Entity 에는 물론 절대 사용해서는 안되는걸로 알고있습니다! 단순 데이터 전달 목적인 Dto 객체에만 사용하였는데 이 부분도 좋지 않은 습관인지 궁금합니다!

**[10]** Querydsl 은 JPAQueryFactory 를 주입받아서 사용하면 Interface/Impl 구조를 사용하지 않아도 돼서 이걸 지향 하는게 좋다고 알고있는데 잘못된건지 궁금합니다!

**[14]** @SpringBootTest 사용시 DB 에 직접 테스트하므로 @Transcational 가 필수여서 적용했었습니다. 
@Rollback false 은 테스트 결과를 DB 에 눈으로 확인해보려고 잠시 달았었고 원래는 테스트가 성공적으로 끝나면 자동 Rollback 을 해주는걸로 알고있습니다. 
14 번의 말씀이 잘 이해가 안가지 않았습니다..! 혹시 테스트시 불필요한 부분이랑 readOnly 가 동작하는지 확인하시라는 부분을 한번 더 여쭤봐도 될까요?!

**마지막 질문**이 있는데 생각해보니 제가 도메인에 확실한 개념이 잘 잡히지 않는 것 같습니다. 
회원, 주문, 상품 같은 엔티티를 도메인이라고 알고있으며 DDD 로 개발을 하면 비지니스 로직들이 도메인으로 이동하고 서비스는 엔티티를 호출하는 정도의 얇은 비지니스 로직을 가지게 된다고 알고있습니다. 또한 철저히 분리된다면 변경과 확장에도 용이할 것 같습니다. 도메인 방식을 적용시킨게 MSA 로 알고있습니다.. 제가 여기까지만 알고있는데 혹시 더 알면 좋은 개념이 있다면 키워드 정도라도 알려주시면 정말 감사하겠습니다..!

**Comment by albothyl** [comment]
5. unit 테스트 없음
6. functional 테스트 없음
- https://www.google.com/search?q=%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8+%ED%85%8C%EC%8A%A4%ED%8A%B8+%EC%A2%85%EB%A5%98&oq=%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8+%ED%85%8C%EC%8A%A4%ED%8A%B8+%EC%A2%85%EB%A5%98&aqs=chrome..69i57.4380j0j7&sourceid=chrome&ie=UTF-8
- 테스트의 종류는 아주 다양합니다.
 
1. unit 테스트는 가장 기본이 되는 테스트 입니다. 오직 1개의 클래스를 테스트하는게 목적이고, 그 이외의 디펜던시는 모두 Mock으로 처리하여 순수하게 기능이 원하는대로 동작 하는지를 테스트 합니니다. 
2. functional 테스트는 스프링 프로젝트라면 컨텍스트를 올려서 특정 기능만 input / out을 테스트 합니다. 테스트에 특정 빈을 주입받고 이 빈에 대해서 input / out을 테스트 합니다. 영화관 사이트가 있다고 가정한다면 티켓에 관한 기능만 집중적으로 테스트 합니다. 주로 @Service 단계를 테스트 하는게 목적이라고 보시면 됩니다.
3. integration 테스트는 컨텍스트를 올려서 전체 과정에 대해서 input / out을 테스트 합니다. 위에서 가정한 영화관 사이트에 대해서 외부에서 요청을 받는 @Controller에 직접 mock request를 날려서 response를 확인하는게 되겠네요.


JPA
8. 불필요한 @query 사용
- JPA에서 가장 중요한게 트랜젝션입니다. 사용하는 기능에 따라 하나의 트랜잭션에 묶일수도 있고, 아닐수도 있습니다. 아래 정리된 내용을 읽어보세요.
- https://wwlee94.github.io/category/blog/spring-transactional-precautions/


9. @DaTa 는 어쩔수 없는 경우가 아니라면 지양할 것
- 엔티티든 dto든 가능하다면 불변객체로 만드는게 유지보수에 있어서 좋습니다. @Data를 사용하면 무조건 setter가 들어가기 때문에 예상하지 못한 결과를 발생시킬 수 있습니다.


10. queryDsl에 대한 클래스 네이밍 규칙 찾아볼 것.
- 말씀하신 내용이 정리된  사이트가 있으면 공유 부탁드립니다. 제가 저렇게 적은건 하나의 repository로 모든 쿼리를 실행할 수 있습니다. 분리할 경우 경우에 따라서 각각 클래스가 분리될 것이고, 사용하는 측면에 있어서 번거롭겠죠.

14. @transactional 에 대한 동작이 어떻게 되는지 공부할 것. (테스트에서 불필요하게 사용되는것, readOlny가 동작 하는지 확인)
- @Transactional(readOnly=true) 기본적으로 read transaction을 분리하기 위한 목적으로 사용됩니다. DB는 가장 비싼 자원입니다. 때문에 1개의 db에서 read/write를 모두 수행하면 traffic이 증가할때 확장하기 힘듭니다. 또한 H/A 구성을 위해서도 좋구요. 그래서 read transaction을 분리하여 1 write / n read로 구성합니다. 그렇다면 프로젝트에서 그냥 @Transactional(readOnly=true)를 사용한다고 해서 read db로 접속할까요? 아니요. 어딘가에서 설정을 해줘야 합니다. 이런 목적이나 설정 없이 그냥 사용하는건 아무것도 모르고 사용했어요 라고 말하는것과 같습니다. 개발한 코드에 대해서 질문이 들어왔을때 이렇게 한 이유를 말할 수 있어야 합니다.


** DDD
DDD는 매우 어렵습니다. 어려운 이유는 추상적인 개념이기 때문입니다. 여기에서 말하기에는 너무 복잡하고 많은 내용이므로 생략하고, 우선 실력을 제대로 키우고 싶으시다면 힘들더라도 아래와 같이 해보세요.

1. 토비 스프링 정독 2회
- 스프링의 기능, 사용법을 알고, 객체 지향 개념을 명확히 한다.

2. jpa
- jpa는 아주 다양한 기능을 편하게 사용할 수 있게 해줍니다. 하지만 명확하게 이 기능이 내부적으로 어떻게 동작하는지는 숨겨져 있죠. 때문에 결과는 내가 원한대로 나와도 내부적으로는 그렇지 않을 수 있습니다. 김영한님 책이나 인프런으로 학습하셔서 JPA에 대해서 꼼꼼히 공부하는게 좋습니다.

3. DDD 
- 최범균님이 쓴 DDD 책을 읽여보세요. 그나마 가장 쉽습니다.
- https://www.coupang.com/vp/products/73052291?itemId=243515565&vendorItemId=3114412421&q=%EC%B5%9C%EB%B2%94%EA%B7%A0&itemsCount=18&searchId=df3890704ae94f33bbc333270612ae7b&rank=3&isAddedCart=

**Comment by albothyl** [comment]
다른 도움이 필요하시다면 이메일주소 남겨주세요.

**Comment by BeomjunLee** [comment]
답변 감사합니다!!
https://www.youtube.com/watch?v=zMAX7g6rO_Y 
우아콘 Querydsl 편에서 봤었습니다! 여러가지 좋은 내용들이 있지만 extends/Impl - > JPAQueryFactory 주입 방식은 1:46초부터 나옵니다!

제 이메일 주소는 qjawnswkd0717@gmail.com 입니다!
